### PR TITLE
Policy drop off point

### LINKED ISSUE #172: Create Policy Drop Off Point
What: https://docs.google.com/document/d/1_lRcJBDzk_GVl-KngzlZAw8i1Oow1mTCISTak4-r0jA/edit#bookmark=id.xl942olrnblt

### PR DESCRIPTION
**Pull request by nhivn**
### Pull Request Checklist ###
- [x] Have you used any third party libraries or softwrae?
  - [x] Have you checked the [license is acceptable?](https://github.com/sardap/Capstone-2019-Data-Sharing/wiki/%2384_spike_acceptable_licenses)
  - [ ] Have you updated the [third party library doc?](https://docs.google.com/spreadsheets/d/1JBfES5GyR0PX2k0xXWG1XyFLgJ7_VYJK9HWqUOIve1s/edit#gid=0)
- [ ] Is there a Readme for the component if applicable ([Example](https://github.com/sardap/Capstone-2019-Data-Sharing/blob/Development/src/BCF/Fetcher/README.md))
  - [ ] Does the Readme include testing information?

- AWS database has been updated to contain the new `UserTokenLinkings` table

### Related issues
This resolves #172

### CODE REVIEW

**Comment by nhivn** [comment]
@Davis-A 
With you to deploy using Docker 🙂

**Comment by sardap** [comment]
@nhivn Is there a setup file for this?

**Comment by Davis-A** [comment]
Paul contacted me that there is a major error in the design of this.   totally not your fault Nhi, this was 100% to spec.  But the spec was wrong.  

When a Broker initiates the process of creating a policy.  A policy creation token is returned to the broker to work as a unique id.  

Problem 1:  The consortium never receives the user\_id of the data subject.  So the field in dropoff point shouldn't be there.  

The dropoff point now only receives the token and the policy location.  Which creates,  
Problem 2:    The Broker needs to have an internal mapping of for every policytoken:user\_id.  I'm thinking a simple two column table where the policy_creation_token is unique and matches to a userid.  

Then when the dropoff point gets a POST.  It can query that table to get the user\_id.

**Comment by nhivn** [comment]
- Remove the user_id as a param from the request in the policy drop off point

**Pull request merged**
